# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gtheurillat\workspace\MR_Sniffer\src\gui\Sniffer.ui'
#
# Created: Wed Oct 01 15:02:53 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName(_fromUtf8("GroupBox"))
        GroupBox.resize(804, 510)
        self.verticalLayoutWidget = QtGui.QWidget(GroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 450, 639))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.listLetters = QtGui.QComboBox(self.verticalLayoutWidget)
        self.listLetters.setObjectName(_fromUtf8("listLetters"))
        self.horizontalLayout.addWidget(self.listLetters)
        self.listSerie = QtGui.QComboBox(self.verticalLayoutWidget)
        self.listSerie.setObjectName(_fromUtf8("listSerie"))
        self.horizontalLayout.addWidget(self.listSerie)
        self.showDetailsButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.showDetailsButton.setObjectName(_fromUtf8("showDetailsButton"))
        self.horizontalLayout.addWidget(self.showDetailsButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.listChapters2 = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listChapters2.setObjectName(_fromUtf8("listChapters2"))
        self.verticalLayout_3.addWidget(self.listChapters2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_10.addWidget(self.label_2)
        self.serie_titre = QtGui.QLabel(self.verticalLayoutWidget)
        self.serie_titre.setObjectName(_fromUtf8("serie_titre"))
        self.horizontalLayout_10.addWidget(self.serie_titre)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.serie_titre_alternatif = QtGui.QLabel(self.verticalLayoutWidget)
        self.serie_titre_alternatif.setObjectName(_fromUtf8("serie_titre_alternatif"))
        self.horizontalLayout_11.addWidget(self.serie_titre_alternatif)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.serie_realease_year = QtGui.QLabel(self.verticalLayoutWidget)
        self.serie_realease_year.setObjectName(_fromUtf8("serie_realease_year"))
        self.horizontalLayout_12.addWidget(self.serie_realease_year)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.serie_auteur = QtGui.QLabel(self.verticalLayoutWidget)
        self.serie_auteur.setObjectName(_fromUtf8("serie_auteur"))
        self.horizontalLayout_13.addWidget(self.serie_auteur)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_14.addWidget(self.label_7)
        self.serie_artiste = QtGui.QLabel(self.verticalLayoutWidget)
        self.serie_artiste.setObjectName(_fromUtf8("serie_artiste"))
        self.horizontalLayout_14.addWidget(self.serie_artiste)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_15.addWidget(self.label_8)
        self.serie_reading_direction = QtGui.QLabel(self.verticalLayoutWidget)
        self.serie_reading_direction.setObjectName(_fromUtf8("serie_reading_direction"))
        self.horizontalLayout_15.addWidget(self.serie_reading_direction)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_16.addWidget(self.label_9)
        self.serie_genre = QtGui.QLabel(self.verticalLayoutWidget)
        self.serie_genre.setObjectName(_fromUtf8("serie_genre"))
        self.horizontalLayout_16.addWidget(self.serie_genre)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.delExistingChapters = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.delExistingChapters.setObjectName(_fromUtf8("delExistingChapters"))
        self.verticalLayout.addWidget(self.delExistingChapters)
        self.select_unselectChapters = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.select_unselectChapters.setObjectName(_fromUtf8("select_unselectChapters"))
        self.verticalLayout.addWidget(self.select_unselectChapters)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.outputText = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.outputText.setObjectName(_fromUtf8("outputText"))
        self.horizontalLayout_8.addWidget(self.outputText)
        self.outputButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.outputButton.setObjectName(_fromUtf8("outputButton"))
        self.horizontalLayout_8.addWidget(self.outputButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.runButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.verticalLayout.addWidget(self.runButton)
        self.progressBar = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.logText = QtGui.QPlainTextEdit(self.verticalLayoutWidget)
        self.logText.setObjectName(_fromUtf8("logText"))
        self.verticalLayout.addWidget(self.logText)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox", None))
        GroupBox.setTitle(_translate("GroupBox", "MangaReader Sniffer v1.0", None))
        self.label_3.setText(_translate("GroupBox", "Serie", None))
        self.showDetailsButton.setText(_translate("GroupBox", "Show", None))
        self.label.setText(_translate("GroupBox", "Titre", None))
        self.label_2.setText(_translate("GroupBox", "Titre", None))
        self.serie_titre.setText(_translate("GroupBox", "TextLabel", None))
        self.label_4.setText(_translate("GroupBox", "Titre Alternatif", None))
        self.serie_titre_alternatif.setText(_translate("GroupBox", "TextLabel", None))
        self.label_5.setText(_translate("GroupBox", "Année de publication", None))
        self.serie_realease_year.setText(_translate("GroupBox", "TextLabel", None))
        self.label_6.setText(_translate("GroupBox", "Auteur", None))
        self.serie_auteur.setText(_translate("GroupBox", "TextLabel", None))
        self.label_7.setText(_translate("GroupBox", "Artiste", None))
        self.serie_artiste.setText(_translate("GroupBox", "TextLabel", None))
        self.label_8.setText(_translate("GroupBox", "Sens de lécture", None))
        self.serie_reading_direction.setText(_translate("GroupBox", "TextLabel", None))
        self.label_9.setText(_translate("GroupBox", "Genre", None))
        self.serie_genre.setText(_translate("GroupBox", "TextLabel", None))
        self.delExistingChapters.setText(_translate("GroupBox", "Ecraser si le chapitre existe deja?", None))
        self.select_unselectChapters.setText(_translate("GroupBox", "Select/unselact all chapters", None))
        self.outputButton.setText(_translate("GroupBox", "Rep sortie", None))
        self.runButton.setText(_translate("GroupBox", "C\'est partie!", None))

